// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeApp.Models;

namespace PracticeApp.Migrations
{
    [DbContext(typeof(RecipesDbContext))]
    [Migration("20220415032310_numberone")]
    partial class numberone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24");

            modelBuilder.Entity("PracticeApp.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumIngredients")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PrepTimeInMinutes")
                        .HasColumnType("REAL");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServingSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeID");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeID = 1,
                            Notes = "Best in a large stanley cup. Enjoy throughout the day.",
                            NumIngredients = 3,
                            PrepTimeInMinutes = 2.0,
                            RecipeName = "Dirty Diet Coke",
                            RecipeType = "Drink",
                            ServingSize = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
